Repository DSM-PICK/PICK2023_FRONT_ADMIN, pull requests merged in 2023-03, with the labels that each got.

#30 🔀 :: (#29) common button style 추가
  src/components/common/button/ButtonComponent.tsx
Labels: chore

#34 🔀 :: (#31) 인원변경 - 반 페이지 퍼블리싱
  src/assets/studentList/arrow.tsx
  src/components/changePersonClass/EditButton.tsx
  src/components/changePersonClass/StudentList.tsx
  src/components/common/dropDown/index.tsx
  src/components/common/outSideClickHandler/index.tsx
  src/pages/change-person/class.tsx
  src/utils/media.ts
Labels: 기능 추가

#32 🔀 :: (#26) PICK ADMIN 인원변경(동아리) 퍼블리싱
  src/assets/club/index.ts
  src/assets/club/king.svg
  src/assets/club/more.svg
  src/components/club/DropDownItem.ts
  src/components/club/member.tsx
  src/components/club/menu.tsx
  src/pages/club/index.tsx
Labels: chore, 기능 추가

#39 🔀 :: (#36) etc setting
  .gitignore
  package.json
  src/assets/navigation/list.tsx
  src/components/.gitkeep
  src/components/main/Date.tsx
  src/components/sidebar/DropDownItem.tsx
  src/components/sidebar/Item.tsx
  src/components/sidebar/SidebarLayout.tsx
  src/models/.gitkeep
  src/models/outing/request.ts
  src/models/outing/response.ts
  src/models/selfStudy/request.ts
  src/models/selfStudy/response.ts
  src/pages/ChangeTeacher.tsx
  src/pages/change-person/class.tsx
  src/pages/change-person/club.tsx
  src/pages/outlist.tsx
  src/utils/.gitkeep
  src/utils/api/common/index.ts
  src/utils/api/outing/index.ts
  src/utils/api/selfStudy/index.ts
  src/utils/axios/index.ts
  src/utils/functions/media.ts
  src/utils/functions/todayDate.ts
  src/utils/functions/tokenManager.ts
  yarn.lock
Labels: chore, 기능 추가

#42 🔀 :: (#41) customStyle 타입설정
  src/components/common/button/ButtonComponent.tsx
Labels: chore

#40 🔀 :: (#38) 외출/이동 수락페이지 ui크기조정
  src/components/activityAccept/DropDownItem.ts
  src/components/activityAccept/MovingComponent.tsx
  src/components/activityAccept/OutingComponent.tsx
  src/pages/activity-accept.tsx
Labels: chore

#45 🔀 :: (#44) 어드민 main api 연결
  src/apis/.gitkeep
  src/components/main/Card.tsx
  src/components/main/Date.tsx
  src/components/sidebar/SidebarLayout.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: chore, 기능 추가

#48 🔀 :: (#47) api url 변경
  src/utils/api/common/index.ts
  src/utils/api/outing/index.ts
  src/utils/api/selfStudy/index.ts
Labels: chore

#50 🔀 :: (#22) 출결상태 페이지 퍼블리싱
  package.json
  src/assets/attendanceState/CalendarIcon.svg
  src/assets/attendanceState/index.ts
  src/components/attendanceState/constants/index.ts
  src/components/attendanceState/index.tsx
  src/components/common/dropDown/index.tsx
  yarn.lock
Labels: 기능 추가

#55 🔀:: (#53) error 처리 및 toast 추가
  package.json
  src/hooks/useApiError.ts
  src/pages/_app.tsx
  yarn.lock
Labels: chore, 기능 추가

#54 🔀 :: (#37) PICK ADMIN 인원변경(방과후) 퍼블리싱 모달추가
  .env
  src/components/club/DropDownItem.ts
  src/components/club/clubDropDown.tsx
  src/components/club/member.tsx
  src/pages/change-person/club.tsx
Labels: chore, 기능 추가

#35 🔀 :: (#33) PICK ADMIN 인원변경(방과후 자습)페이지 퍼블리싱
  src/assets/AfterSchool/delete.svg
  src/assets/AfterSchool/index.ts
  src/components/personnelChange/AfterSchool.tsx
  src/components/personnelChange/List.ts
  src/components/sidebar/DropDownItem.tsx
  src/pages/change-person/afterSchool.tsx
  src/pages/change-person/index.tsx
  yarn.lock
Labels: 기능 추가

#57 🔀:: (#49) 외출복귀 및 반 인원변경 퍼블리싱 & api연결
  .env
  src/components/OutList/outing.tsx
  src/components/changePersonClass/StudentList.tsx
  src/hooks/usePeriod.ts
  src/pages/change-person/class.tsx
  src/pages/outlist.tsx
  src/utils/api/changePerson/index.ts
  src/utils/constant/statusMap.ts
Labels: chore, 기능 추가

#59 🔀 :: (#56) club api 연결
  src/components/club/clubDropDown.tsx
  src/components/club/member.tsx
  src/components/sidebar/DropDownItem.tsx
  src/constants/DropDownItem.ts
  src/models/selfStudy/request.ts
  src/models/selfStudy/response.ts
  src/pages/change-person/club.tsx
  src/utils/api/selfStudy/index.ts
Labels: chore, 기능 추가

#62 🔀 :: (#58) 자습감독선생변경
  src/assets/changeTeacher/calendarArrow.svg
  src/assets/changeTeacher/index.tsx
  src/components/changeTeacher/calendar.tsx
  src/components/changeTeacher/modal.tsx
  src/components/changeTeacher/teacher.tsx
  src/components/sidebar/SidebarLayout.tsx
  src/pages/ChangeTeacher.tsx
  src/pages/change-person/class.tsx
  src/pages/changeTeacher.tsx
  src/utils/api/common/index.ts
  src/utils/api/selfStudy/index.ts
Labels: chore, 기능 추가

#63 🔀 :: (#51) 출결상태 페이지 API 연동
  src/components/attendanceState/dropDown/index.tsx
  src/components/attendanceState/index.tsx
  src/components/common/dropDown/index.tsx
  src/models/selfStudy/request.ts
  src/utils/api/selfStudy/index.ts
Labels: 기능 추가

#66 🔀 :: (#64) 출결상태 페이지 수정
  src/components/attendanceState/index.tsx
  src/components/common/dropDown/index.tsx
Labels: chore

#65 🔀 :: (#61) 인원변경 방과후 페이지 퍼블리싱 및 api 연동
  src/components/personnelChange/AfterSchool.tsx
  src/components/personnelChange/List.ts
  src/components/personnelChange/List.tsx
  src/models/selfStudy/response.ts
  src/pages/api/hello.ts
  src/pages/change-person/afterSchool.tsx
  src/pages/change-person/index.tsx
  src/utils/api/selfStudy/index.ts
  tsconfig.json
  yarn.lock
Labels: 기능 추가

#67 🔀 :: (#60) outing accept api
  src/components/OutList/outing.tsx
  src/components/activityAccept/DropDownItem.ts
  src/components/activityAccept/MovingComponent.tsx
  src/components/activityAccept/OutingComponent.tsx
  src/components/common/button/ButtonComponent.tsx
  src/components/main/Date.tsx
  src/components/personnelChange/AfterSchool.tsx
  src/models/outing/request.ts
  src/models/outing/response.ts
  src/models/selfStudy/request.ts
  src/pages/activity-accept.tsx
  src/pages/outlist.tsx
  src/store/createSlice.ts
  src/utils/api/outing/index.ts
  src/utils/api/selfStudy/index.ts
Labels: chore, 기능 추가

#69 🔀 :: (#68) 전체적인 코드 리팩토링
  src/assets/changeTeacher/index.tsx
  src/components/OutList/outing.tsx
  src/components/activityAccept/ButtonBox.tsx
  src/components/activityAccept/Filter.tsx
  src/components/activityAccept/HeadBar.tsx
  src/components/activityAccept/MovingComponent.tsx
  src/components/activityAccept/OutingComponent.tsx
  src/components/activityAccept/OutingList.tsx
  src/components/activityAccept/ToggleFloor.tsx
  src/components/attendanceState/constants/index.ts
  src/components/attendanceState/index.tsx
  src/components/changePersonClass/StudentList.tsx
  src/components/changeTeacher/modal.tsx
  src/components/changeTeacher/teacher.tsx
  src/components/club/clubDropDown.tsx
  src/components/club/member.tsx
  src/components/common/Button.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Input.tsx
  src/components/common/Modal.tsx
  src/components/common/OutSideClickHandler.tsx
  src/components/common/PageContainer.tsx
  src/components/common/Title.tsx
  src/components/main/Card.tsx
  src/components/personnelChange/AfterSchool.tsx
  src/components/personnelChange/List.tsx
  src/pages/activity-accept.tsx
  src/pages/change-person/afterSchool.tsx
  src/pages/change-person/class.tsx
  src/pages/change-person/club.tsx
  src/pages/changeTeacher.tsx
  src/pages/index.tsx
  src/pages/main.tsx
  src/pages/outlist.tsx
  src/utils/api/selfStudy/index.ts
Labels: chore

#72 🔀 :: 출결상태 페이지 컴포넌트화 + 반응형
  src/components/attendance/CalenderFilter.tsx
  src/components/attendance/ClassDropDown.tsx
  src/components/attendance/Filter.tsx
  src/components/attendance/Header.tsx
  src/components/attendance/List.tsx
  src/components/attendance/constants/index.ts
  src/components/attendance/index.tsx
  src/components/common/Dropdown.tsx
  src/pages/attendance.tsx
Labels: 리팩토링

#73 🔀 :: (#71) 에러 처리 및 토스트
  src/components/OutList/outing.tsx
  src/components/activityAccept/ButtonBox.tsx
  src/components/activityAccept/Filter.tsx
  src/components/attendance/List.tsx
  src/components/attendance/index.tsx
  src/components/changeTeacher/modal.tsx
  src/components/club/member.tsx
  src/components/personnelChange/List.tsx
  src/components/sidebar/SidebarLayout.tsx
  src/hooks/useApiError.ts
  src/pages/activity-accept.tsx
  src/pages/change-person/afterSchool.tsx
  src/pages/change-person/class.tsx
  src/pages/change-person/club.tsx
  src/pages/main.tsx
  src/pages/outlist.tsx
  src/utils/api/selfStudy/index.ts
Labels: chore

#80 🔀 :: (#74) etc
  src/components/changeTeacher/teacher.tsx
  src/hooks/useApiError.ts
  src/pages/activity-accept.tsx
  src/pages/change-person/class.tsx
  src/pages/change-person/club.tsx
  src/pages/outlist.tsx
  src/utils/axios/index.ts
  src/utils/functions/tokenManager.ts
Labels: chore, 기능 추가

#81 🔀 :: (#76) api 두번 호출 에러 + 네이밍 수정
  src/components/outlist/List.tsx
  src/pages/activity-accept.tsx
  src/pages/attendance.tsx
  src/pages/outlist.tsx
  src/utils/api/outing/index.ts
Labels: chore, 버그
