Repository DSM-PICK/PICK2023_FRONT_ADMIN, pull requests merged in 2023-02, with the labels that each got.

#7 🔀 :: (#1) make navigation
  src/assets/.gitkeep
  src/assets/Logo.svg
  src/assets/navigation/check.tsx
  src/assets/navigation/index.ts
  src/assets/navigation/list.tsx
  src/assets/navigation/out.tsx
  src/assets/navigation/people.tsx
  src/assets/navigation/teacher.tsx
  src/assets/navigation/vector.tsx
  src/components/sidebar/DropDownItem.tsx
  src/components/sidebar/Item.tsx
  src/components/sidebar/SidebarLayout.tsx
  src/pages/_app.tsx
Labels: chore, 기능 추가

#9 🔀 :: (#8) ButtonComponent
  src/common/Button/ButtonComponent.tsx
  src/common/Button/constants/index.ts
Labels: 기능 추가

#5 🔀 :: (#3)PICK ADMIN 외출자목록 페이지 퍼블리싱
  src/components/OutList/index.tsx
  src/components/OutList/outing.tsx
Labels: 기능 추가

#4 🔀 :: (#5)PICK ADMIN 메인페이지 퍼블리싱
  package.json
  src/assets/index.js
  src/assets/index.tsx
  src/assets/main/Attendance.svg
  src/assets/main/Outing.svg
  src/assets/main/OutingList.svg
  src/assets/main/index.ts
  src/components/main/index.tsx
  src/pages/index.tsx
  yarn.lock
Labels: 기능 추가

#15 🔀 :: (#13) PICK ADMIN 드롭다운 제작
  src/assets/dropDown/DropDownIcon.svg
  src/assets/dropDown/index.ts
  src/components/common/button/ButtonComponent.tsx
  src/components/common/button/constants/index.ts
  src/components/common/dropDown/index.tsx
  src/models/common/index.ts
Labels: 기능 추가

#17 🔀 :: (#16) PICK ADMIN 메인페이지 수정
  src/assets/main/Attendance.svg
  src/assets/main/Outing.svg
  src/assets/main/OutingList.svg
  src/common/Button/ButtonComponent.tsx
  src/common/Button/constants/index.ts
  src/common/dropDown/index.tsx
  src/components/main/index.tsx
  src/pages/index.tsx
Labels: chore

#21 🔀 :: (#14) PICK ADMIN 외출/이동 수락 페이지 퍼블리싱
  package.json
  src/assets/ActivityAccept/arrow.svg
  src/assets/ActivityAccept/index.ts
  src/components/activityAccept/MovingComponent.tsx
  src/components/activityAccept/OutingComponent.tsx
  src/components/activityAccept/ToggleFloor.tsx
  src/pages/activity-accept.tsx
  yarn.lock
Labels: chore, 기능 추가

#23 #20 modify sidebar
  src/components/OutList/index.tsx
  src/components/main/index.tsx
  src/components/sidebar/DropDownItem.tsx
  src/components/sidebar/Item.tsx
  src/components/sidebar/SidebarLayout.tsx
  src/pages/_app.tsx
  src/pages/outlist/index.tsx
Labels: chore

#25 🔀 :: (#16) PICK ADMIN 메인페이지 수정
  src/components/main/index.tsx
Labels: chore
